name: Client - Deploy client main app development stage

on:
  workflow_dispatch:
    inputs:
      project:
        description: "Project"
        required: true
        type: choice
        options:
          - enterprise
          - multi-tenant

jobs:
  deploy:
    runs-on: ubuntu-latest # runner
    defaults:
      run:
        working-directory: ./front

    permissions:
      contents: read
      id-token: write # google-github-actions/auth 액션 사용하기 위해 필요하다.

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set variables
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          echo "stage=dev" >> "$GITHUB_OUTPUT"

      - name: Check variables
        run: |
          echo "sha_short: ${{ steps.vars.outputs.sha_short }}"

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.27.0

      - name: Set environment variables
        run: |
          cd /apps/main-app
          echo "NEXT_PUBLIC_HUB_API_HOST='https://hub-${{ steps.vars.outputs.stage }}.airklass.com'" >> .env.production
          echo "NEXT_PUBLIC_ASSET_PREFIX='https://shared.static.airklass.com/front/main-app/${{ steps.vars.outputs.stage }}/${{ steps.vars.outputs.sha_short}}'" >> .env.production

      - name: Install dependencies
        run: pnpm install

      - name: Build main app project
        run: pnpm -w run build-main-app

      - name: Authenticate google cloud storage
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/395494119178/locations/global/workloadIdentityPools/github-action/providers/github-action-oidc"
          service_account: "github-action-deploy@shared-resource-366111.iam.gserviceaccount.com"

      - name: Upload static folder to GCS
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: apps/main-app/build/static
          destination: shared.static.airklass.com/front/main-app/${{ steps.vars.outputs.stage }}/${{ steps.vars.outputs.sha_short}}/_next
          process_gcloudignore: false
