name: Client - Deploy client main app development stage

on:
  workflow_dispatch:
    inputs:
      project:
        description: "Project"
        required: true
        type: choice
        options:
          - enterprise
          - multi-tenant

jobs:
  deploy:
    runs-on: ubuntu-latest # runner
    env:
      working-directory: ./front

    permissions:
      contents: read
      id-token: write # google-github-actions/auth 액션 사용하기 위해 필요하다.

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set variables
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          echo "stage=dev" >> "$GITHUB_OUTPUT"

      - name: Check variables
        run: |
          echo "sha_short: ${{ steps.vars.outputs.sha_short }}"

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.27.0

      - name: Set environment variables
        run: |
          cd ./apps/main-app
          echo "NEXT_PUBLIC_HUB_API_HOST='https://hub-${{ steps.vars.outputs.stage }}.airklass.com'" >> .env.production
          echo "NEXT_PUBLIC_ASSET_PREFIX='https://shared.static.airklass.com/front/main-app/${{ steps.vars.outputs.stage }}/${{ steps.vars.outputs.sha_short}}'" >> .env.production
        working-directory: ${{ env.working-directory }}

      - name: Install dependencies
        run: pnpm install
        working-directory: ${{ env.working-directory }}

      - name: Build main app project
        run: pnpm -w run build-main-app
        working-directory: ${{ env.working-directory }}

      - name: Authenticate to project Shared Resource
        uses: "google-github-actions/auth@v1"
        id: "auth"
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/395494119178/locations/global/workloadIdentityPools/github-action/providers/github-action-oidc"
          service_account: "github-action-deploy@shared-resource-366111.iam.gserviceaccount.com"
          access_token_lifetime: 300s

      - name: Upload static folder to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: front/apps/main-app/build/static
          destination: shared.static.airklass.com/front/main-app/${{ steps.vars.outputs.stage }}/${{ steps.vars.outputs.sha_short}}/_next
          process_gcloudignore: false

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: asia-northeast3-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: asia-northeast3-docker.pkg.dev/multi-tenant-biz1/front/main-app
          flavor: |
            latest=true
          tags: |
            type=${{ steps.vars.outputs.sha_short }}
            type=${{ steps.vars.outputs.stage }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./front/apps/main-app/build/standalone
          file: ./front/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
