
name: Deploy TEST

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Deploy by a tag'
        required: true
        type: boolean

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run |
          echo "HELLO"
          echo "TAGS: $TAGS"