name: Deploy client main app development stage

on:
  workflow_dispatch:
    inputs:
      project:
        description: "Project"
        required: true
        type: choice
        options:
          - enterprise
          - multi-tenant

jobs:
  deploy:
    runs-on: ubuntu-latest # runner

    permissions:
      contents: read
      id-token: write # google-github-actions/auth 액션 사용하기 위해 필요하다.

    env:
      SHA_SHORT: $(git rev-parse --short HEAD)

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set variables
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Check variables
        run: |
          echo "sha_short: ${{ steps.vars.outputs.sha_short }}"
